name: social_media_audio_recorder
description: A flutter package that use for build animated voice recorder as like other social media.
version: 0.0.12
homepage: https://github.com/xeeshan400/social_media_audio_recorder.git

environment:
  sdk: '>=3.5.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^11.3.1
  path_provider: ^2.0.15
  record: ^5.1.2
#  flutter_vibrate: ^1.3.0
  lottie: ^3.0.0
  font_awesome_flutter: ^10.3.0
  vibration: ^3.1.3





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/dustbin.json
    - assets/dustbin_grey.json

